### ISSUE TITLE
Running the image with "generate" argument yields invalid yaml in <servername>.log.config file

### ISSUE THREAD

**Issue by ghost** [AVENTER-UG/docker-matrix#10]
filename key needs to be indented:

~~~
version: 1

formatters:
    precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

filters:
    context:
        (): synapse.util.logcontext.LoggingContextFilter
        request: ""

handlers:
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: precise
    filename: /data/homeserver.log
        maxBytes: 104857600
        backupCount: 10
        filters: [context]
    console:
        class: logging.StreamHandler
        formatter: precise
        filters: [context]

loggers:
    synapse:
        level: INFO

    synapse.storage.SQL:
        # beware: increasing this to DEBUG will make synapse log sensitive
        # information such as access tokens.
        level: INFO

root:
    level: INFO
    handlers: [file, console]
/tmp/data/localhost.log.config (END)
~~~

**Comment by m4teh** [comment]
Same issue. Unable to bring up the instance at all with this bug.

**Comment by ghost** [comment]
@m4teh you tried to just indent the filename key or were you just describing the broader issue resulting from that?

**Comment by m4teh** [comment]
Just describing the broader issue.
Once I add the necessary spaces to the line, the instance initiates and the problem is solved.

**Comment by ghost** [comment]
Alright thanks! I quickly tried to find the root of the problem in the code but wasn't able to locate it so far.

**Comment by mvgorcum** [comment]
I've looked in to this, and it seems to be an issue with synapse, and not the docker version. I've opened an issue on the synapse github [here](https://github.com/matrix-org/synapse/issues/3065).

**Comment by ghost** [comment]
@mvgorcum Thank you for looking into it! :)

**Comment by mvgorcum** [comment]
Turns out I was wrong and it was an issue with start.sh it should be fixed with the next rebuild.
