### ISSUE TITLE
Track latest stable release as tag

### ISSUE THREAD

**Issue by Nebukadneza** [AVENTER-UG/docker-matrix#22]
Hello,

thanks for the nice and convenient matrix-images you provide. I have one suggestion for them. In `README.MD`, you write that `Please make sure to use our tagged docker images and not the latest one.`. While this is true, it’d be great to have a tag that follows the latest stable version — let’s call it `production`, `stable`, or whatever. This would enable users to who automatically update all their docker images e.g. using https://github.com/circa10a/ouroboros or https://github.com/v2tec/watchtower to enter that tag in their docker-compose files and still follow the latest stable releases and build. This can be useful, as seen with the current release, which contains urgent security fixes ….

Thanks & Best,
-Dario

**Comment by andreaspeters** [comment]
Hi Dario,

thanks for your issue. This is definitely a good idea. We will think about it.

Best,
Andreas
