### ISSUE TITLE
Switch to postgres

### ISSUE THREAD

**Issue by ghost** [AVENTER-UG/docker-matrix#24]
The community favors postgres as the database-backend of synapse for performance reasons. Why does this image not use postgres?

**Comment by mvgorcum** [comment]
It defaults to sqlite just like synapse itself, you can still use postgresql though. (I do) 

[Edit] maybe we should write a guide on how to move to posgres, though.

**Comment by ghost** [comment]
Does the container include postgres out of the box? Since it is an all-in-one, maybe it should?

**Comment by mvgorcum** [comment]
I would argue against including postgresql, I really prefer SQL databases running on bare metal rather than containers, but even if you did you should set it up using a separate container.

**Comment by ghost** [comment]
The oznu/docker-guacamole and thetarkus/docker-funkwhale containers both include postgres out of the box and they run fine on my NAS. For the sake of sensible defaults, I think postgres is a better choice than sqlite.

**Comment by mvgorcum** [comment]
The thing with synapse is that if you lose your database, you'll face some serious issues, and starting with a clean server on the same URL on federated servers will be problematic.

**Comment by andreaspeters** [comment]
to bring this issue to the end. if you want to use postgresql in the same container like synapse, then its better to use a other containers as our one. we will not include a server based database in the container.
