### ISSUE TITLE
Switch image to Python 3?

### ISSUE THREAD

**Issue by lbeltrame** [AVENTER-UG/docker-matrix#25]
As the subject says, it might be useful given the improvements reported by the Matrix team.

**Comment by mvgorcum** [comment]
There are images with a python 3 base available on [docker hub](https://hub.docker.com/r/avhost/docker-matrix/tags) tagged as .dev.py3. These images work, but have the downside of running synapse as root and being bigger. Once I have some time I'll finish the dockerfile and try to move the main images to python 3.

If you happen to have some time you can find the python 3 dockerfile [here](https://github.com/mvgorcum/docker-matrix/tree/python3). I welcome PR's.

**Comment by andreaspeters** [comment]
Image is switched to python3 now. :-)
