### ISSUE TITLE
1.3.1 image broken?

### ISSUE THREAD

**Issue by motey** [AVENTER-UG/docker-matrix#38]
when trying to update to the newest avhost/docker-matrix:v1.3.1 image, it fails to start synapse
logs outputs:
```
-=> start turn
-=> start matrix
Cannot create pid file: /var/run/turnserver.pid: Permission denied

Unable to find template file /usr/local/lib/python3.5/dist-packages/synapse/res/templates/password_reset.html
```
Is that reproducible for somebody else?

**Comment by motey** [comment]
maybe related https://github.com/silvio/docker-matrix/issues/23

**Comment by andreaspeters** [comment]
Hi @motey ,

well, the permission denied failure is not pretty buts its actually not a failure. The pid file will be under /tmp. And its definitely not related to the failure that your template could not be found. Without the have a look at your configuration file, I think the path to the template is in the homeserver.yaml wrong.

**Comment by motey** [comment]
Thanks for the reply. yep, my fault. I did not realize the switch from python 3.5 to python 3.7. Resulted in some pathes in the config were wrong for me. Sorry for bothering
Thanks for your work, have a good week.
