### ISSUE TITLE
docker run generate / start.sh: fails on systems running docker as non-root user

### ISSUE THREAD

**Issue by kidwellj** [AVENTER-UG/docker-matrix#40]
As per here: https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user my docker instance is set up to run as a non-root user. This is somewhat unusual but not uncommon. I'm pretty sure this is causing my attempts to run `docker run -v /tmp/matrixdata:/data --rm -e SERVER_NAME=localhost -e REPORT_STATS=no avhost/docker-matrix:v1.9.1 generate` (not my exact command, but you get the idea) to fail:

```
-=> generate turn config
/start.sh: line 14: /data/turnserver.conf: Permission denied
/start.sh: line 15: /data/turnserver.conf: Permission denied
/start.sh: line 16: /data/turnserver.conf: Permission denied
/start.sh: line 17: /data/turnserver.conf: Permission denied
/start.sh: line 18: /data/turnserver.conf: Permission denied
/start.sh: line 19: /data/turnserver.conf: Permission denied
/start.sh: line 20: /data/turnserver.conf: Permission denied
/start.sh: line 21: /data/turnserver.conf: Permission denied
-=> generate synapse config
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/synapse/app/homeserver.py", line 639, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/synapse/app/homeserver.py", line 634, in main
    hs = setup(sys.argv[1:])
  File "/usr/local/lib/python3.7/dist-packages/synapse/app/homeserver.py", line 319, in setup
    "Synapse Homeserver", config_options
  File "/usr/local/lib/python3.7/dist-packages/synapse/config/_base.py", line 576, in load_or_generate_config
    with open(config_path, "w") as config_file:
PermissionError: [Errno 13] Permission denied: '/data/homeserver.tmp'
Generating config file /data/homeserver.tmp
-=> configure some settings in homeserver.yaml
awk: cannot open /data/homeserver.tmp (No such file or directory)
mv: cannot create regular file '/data/homeserver.tmp': Permission denied
mv: cannot stat '/data/homeserver.tmp': No such file or directory
```
I've tried running `docker run -v /opt/appdata/matrix/synapse:/data...` using sudo, without and have also tried this with previous docker builds (1.9.0 and 1.7.3) and the issue persists.

I'm pretty sure this is similar to #14 and #8 but comments in those issues don't indicate how users have resolved the problem. As per https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue I've also tried to reboot my system, restart docker, switch around group membership and shift directory permissions on `/opt/appdata/matrix/*`.

Has anyone resolved this before who can comment? Working with Debian 4.9.130-2.

**Comment by mvgorcum** [comment]
You can solve this by chowning the folder (and if they exist the files in that folder) to 991.

**Comment by kidwellj** [comment]
Yep, that was it. Thanks @mvgorcum
