### ISSUE TITLE
sqlite error with turn server

### ISSUE THREAD

**Issue by devz3r0** [AVENTER-UG/docker-matrix#43]
hi,

the images works well thank for that, but the turn server reports:

0: ERROR: Cannot open SQLite DB connection: </var/lib/turn/turndb>, runtime error:
  unable to open database file
  (If your intention is to use an SQLite database for the TURN server, then
  check and fix, if necessary, the effective permissions of the TURN server
  process and of the DB directory and then re-start the TURN server)

is it possible to do a mkdir and chmod 777 of /var/lib/turn/
to get this away?

thanks Martin

**Comment by devz3r0** [comment]
fixed it now with 
docker run -i -t -d --restart=always -p 8448:8448 -p 3478:3478 -p 3478:3478/udp  -v /srv/synapsedata:/data -v /srv/turnstart:/etc/systemd/system/multi-user.target.wants/ avhost/docker-matrix start

and reconfiged the sqlite path in the exposed conf and adjusted the exposed coturn.service systemd file too.

**Comment by mvgorcum** [comment]
By default the turnserver is supposed to run without using a database, so I'm a little puzzled why you run in to this error.

If you need turnserver to use a database I'd recommend configuring turnserver.conf to place a sqlite database in `/data/`

On a related note: if you want to use the turnserver as relay you'll need to expose the udp portrange as well. That's by default `49152-65535` though you can change that with `min-port=` and `max-port=`

**Comment by GnaXi** [comment]
I'm also getting this error with a clean instance of this in docker.
And I cannot for the life of me get the turn server to work.

**Comment by mvgorcum** [comment]
Adding
```
userdb=/data/turndb
```
to `turnserver.conf` should fix it.

**Comment by GnaXi** [comment]
Weirdly enough that didn't work either, when I was playing around with it yesterday.
So I gave up for the day and turned of the docker instance. When I turned the docker instance back on this morning, and without doing any changes, it just worked.
I have no explanation as to what the issue could have been, but I guess the most important thing that it is now working! :P
