### ISSUE TITLE
Unable to start the container on arm64

### ISSUE THREAD

**Issue by iodize6399** [AVENTER-UG/docker-matrix#56]
As the title says, I'm unable to use this on arm host. I've tried `platform:linux/arm64` but all I get is `standard_init_linux.go:228: exec user process caused: exec format error`

**Comment by andreaspeters** [comment]
Thanks @physx2494 , I will have a look.

**Comment by andreaspeters** [comment]
Sorry @physx2494 , I didnt forgot your issue. I only have less time at the moment to take a deeper look . :-(

**Comment by andreaspeters** [comment]
Hi @physx2494, on my site it's working under arm64. Does it works for you with a newer version?
