### ISSUE TITLE
Can't start the server/Generate Config

### ISSUE THREAD

**Issue by aevans1987** [AVENTER-UG/docker-matrix#57]
docker run -v ~/matrix-mmf:/data:rw --rm -e SERVER_NAME={domain} -e REPORT_STATS=no -e MATRIX_UID=1001 -e MATRIX_GID=1001 avhost/docker-matrix:v1.59.1 generate

Running that, gives me this:

-=> generate turn config
/start.sh: line 14: /data/turnserver.conf: Permission denied
/start.sh: line 15: /data/turnserver.conf: Permission denied
/start.sh: line 16: /data/turnserver.conf: Permission denied
/start.sh: line 17: /data/turnserver.conf: Permission denied
/start.sh: line 18: /data/turnserver.conf: Permission denied
/start.sh: line 19: /data/turnserver.conf: Permission denied
/start.sh: line 20: /data/turnserver.conf: Permission denied
-=> generate synapse config
/start.sh: line 21: /data/turnserver.conf: Permission denied
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/synapse/app/homeserver.py", line 460, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/synapse/app/homeserver.py", line 450, in main
    hs = setup(sys.argv[1:])
  File "/usr/local/lib/python3.10/dist-packages/synapse/app/homeserver.py", line 326, in setup
    config = HomeServerConfig.load_or_generate_config(
  File "/usr/local/lib/python3.10/dist-packages/synapse/config/_base.py", line 666, in load_or_generate_config
    with open(config_path, "w") as config_file:
PermissionError: [Errno 13] Permission denied: '/data/homeserver.tmp'
Generating config file /data/homeserver.tmp
-=> configure some settings in homeserver.yaml
awk: cannot open /data/homeserver.tmp (No such file or directory)
mv: cannot create regular file '/data/homeserver.tmp': Permission denied
mv: cannot stat '/data/homeserver.tmp': No such file or directory
-=> configure some settings in {domain}.log.config
sed: can't read /data/{domain}.log.config: No such file or directory

-=> you have to review the generated configuration file homeserver.yaml

ID 1001 is for the ade account.

**Comment by andreaspeters** [comment]
Hi @Jacob-Evans , I think this issue is double. Please take a look into this one:  https://github.com/AVENTER-UG/docker-matrix/issues/40  :-)
