### ISSUE TITLE
v1.174.0 fails with ModuleNotFoundError

### ISSUE THREAD

**Issue by benschweizer** [AVENTER-UG/docker-matrix#61]
Hi,

the latest container doesn't start, i get
```
Error while finding module specification for 'synapse.app.homeserver' (ModuleNotFoundError: No module named 'synapse.app'
```
It works fine with v1.173.0 and I assume some packaging error here.

**Comment by andreaspeters** [comment]
HI @benschweizer, thanks for feedback.  And sorry for the problem. I will have a look at that.

**Comment by andreaspeters** [comment]
I fixed it. :-)
