### ISSUE TITLE
Latest docker image (avhost/docker-matrix:v1.74.0) fails to start.

### ISSUE THREAD

**Issue by Aterfax** [AVENTER-UG/docker-matrix#62]
Image: avhost/docker-matrix:v1.74.0

See: https://forums.unraid.net/topic/89502-support-a75g-repo/?do=findComment&comment=1204926

``` log
/usr/bin/python3: Error while finding module specification for 'synapse.app.homeserver' (ModuleNotFoundError: No module named 'synapse.app')
```

A cursory Google suggests that this may be related:

https://github.com/matrix-org/synapse/issues/4431

**Comment by andreaspeters** [comment]
This issue is already fixed. Please pull the updated v1.74.0 image. :-)  It should have the digest "66ea506afc51".

**Comment by Aterfax** [comment]
So it is, repulling the v1.74.0 sorted things for me.

Many thanks for the fix and the docker image in general!

**Comment by andreaspeters** [comment]
Thanks @Aterfax  😊
