### ISSUE TITLE
pwgen: command not found

### ISSUE THREAD

**Issue by vump** [AVENTER-UG/docker-matrix#65]
I'm trying to generate the example turnserver.yaml and homeserver.yaml. But the generate command keeps failing with the pwgen: command not found. Tried installing it but it does not help.

```
docker run -v /path/to/matrix/data:/data --rm --user 1000:1000 -e SERVER_NAME=matrix.xx.example -e REPORT_STATS=no avhost/docker-matrix:latest generate
```

```
-=> generate turn config
/start.sh: line 205: pwgen: command not found
/start.sh: line 17: : No such file or directory
/start.sh: line 18: : No such file or directory
/start.sh: line 19: : No such file or directory
/start.sh: line 20: : No such file or directory
/start.sh: line 21: : No such file or directory
/start.sh: line 22: : No such file or directory
/start.sh: line 23: : No such file or directory
-=> generate synapse config
/start.sh: line 24: : No such file or directory
Generating config file /data/homeserver.tmp
A config file has been generated in '/data/homeserver.tmp' for server name 'matrix.xx.example'. Please review this file and customise it to your needs.
-=> configure some settings in homeserver.yaml
mv: cannot move '/tmp/tmp.41pwBCogTS' to '': No such file or directory
-=> configure some settings in matrix.xx.example.log.config
```

**Comment by andreaspeters** [comment]
@vump thanks for your issue. I add pwgen in the current version. Please take a look if it's working for u now. :-)

**Comment by vump** [comment]
`Status: Downloaded newer image for avhost/docker-matrix:v1.98.0
-=> generate turn config
-=> generate synapse config
Generating config file /data/homeserver.tmp
A config file has been generated in '/data/homeserver.tmp' for server name 'matrix.xx.example'. Please review this file and customise it to your needs.
-=> configure some settings in homeserver.yaml
-=> configure some settings in matrix.xx.example.log.config

-=> you have to review the generated configuration file homeserver.yaml`

Great success!! Thanks!
