### ISSUE TITLE
Update to v0.26.1

### ISSUE THREAD

**Issue by mvgorcum** [AVENTER-UG/docker-matrix#9]
A malformed event caused a lot of federated servers to crash (including mine).
The new hotfix should fix the issue.

**Comment by andreaspeters** [comment]
hi @mvgorcum, I start a update, but have no time to wait until is finish. Will have a look in 2 hours if it was succesfull.

**Comment by mvgorcum** [comment]
That fixed it.

**Comment by andreaspeters** [comment]
I fix it
